import Image from "next/image"
import { MdxRenderer } from "../mdx-renderer"
import type { PortfolioData, PortfolioRepo } from "@/types/portfolio"

export function MinimalTemplate({ data }: { data: PortfolioData }) {
  const totalStars = data.repositories.reduce((s, r) => s + r.stars_count, 0)

  return (
    <div className="min-h-[100dvh] bg-background text-foreground font-sans">
      {/* Header */}
      <header className="max-w-2xl mx-auto px-6 pt-20 pb-16">
        <div className="flex items-start gap-5 mb-10">
          {data.avatar_url && (
            <Image src={data.avatar_url} alt={data.username} width={64} height={64} className="rounded-full border border-border mt-1 shrink-0" />
          )}
          <div className="flex-1">
            <h1 className="text-xl font-semibold text-foreground">{data.username}</h1>
            <a href={`https://github.com/${data.username}`} target="_blank" rel="noopener noreferrer"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              github.com/{data.username}
            </a>
            <div className="flex items-center gap-4 mt-3 text-xs text-muted-foreground">
              <span>{data.repositories.length} projects</span>
              <span className="w-px h-3 bg-border" />
              <span>{totalStars.toLocaleString()} stars</span>
              <span className="w-px h-3 bg-border" />
              <span>
                {[...new Set(data.repositories.map(r => r.primary_language).filter(Boolean))].join(" · ")}
              </span>
            </div>
          </div>
        </div>

        <div className="prose prose-neutral dark:prose-invert max-w-none text-muted-foreground leading-relaxed">
          <MdxRenderer content={extractIntro(data.mdx_content)} />
        </div>
      </header>

      {/* Projects */}
      <main className="max-w-2xl mx-auto px-6 pb-24">
        <h2 className="text-xs font-medium uppercase tracking-widest text-muted-foreground mb-8">
          Selected Projects
        </h2>

        <div className="space-y-12">
          {data.repositories.map((repo, i) => (
            <MinimalRepoEntry key={repo.id} repo={repo} index={i} />
          ))}
        </div>

        {data.mdx_content && extractRest(data.mdx_content) && (
          <div className="mt-20 pt-16 border-t border-border">
            <h2 className="text-xs font-medium uppercase tracking-widest text-muted-foreground mb-6">More</h2>
            <div className="prose prose-neutral dark:prose-invert max-w-none text-muted-foreground leading-relaxed">
              <MdxRenderer content={extractRest(data.mdx_content)} />
            </div>
          </div>
        )}
      </main>

      <footer className="max-w-2xl mx-auto px-6 py-8 border-t border-border flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          Generated by{" "}
          <a href="/" className="hover:text-foreground transition-colors underline underline-offset-2">Astra</a>
        </p>
        {data.last_synced_at && (
          <p className="text-xs text-muted-foreground">
            Updated {new Date(data.last_synced_at).toLocaleDateString("en-US", { month: "short", year: "numeric" })}
          </p>
        )}
      </footer>
    </div>
  )
}

function MinimalRepoEntry({ repo, index }: { repo: PortfolioRepo; index: number }) {
  const complexity = repo.ast_metadata?.complexity_score ?? 0
  const yearCreated = new Date(repo.created_at).getFullYear()
  const lastUpdated = new Date(repo.updated_at).toLocaleDateString("en-US", { month: "short", year: "numeric" })

  return (
    <article>
      {/* Title row */}
      <div className="flex items-start justify-between gap-4 mb-3">
        <div>
          <div className="flex items-center gap-3 flex-wrap">
            <h3 className="text-base font-semibold text-foreground">{repo.name}</h3>
            {repo.primary_language && (
              <span className="text-xs text-muted-foreground">{repo.primary_language}</span>
            )}
            <span className="text-xs text-muted-foreground/50">{yearCreated}</span>
          </div>
          {repo.description && (
            <p className="text-sm text-muted-foreground mt-1 leading-snug">{repo.description}</p>
          )}
        </div>
        <div className="flex items-center gap-3 shrink-0 text-xs text-muted-foreground">
          {repo.homepage && (
            <a href={repo.homepage} target="_blank" rel="noopener noreferrer"
              className="hover:text-foreground transition-colors underline underline-offset-2">
              demo ↗
            </a>
          )}
          <a href={repo.html_url ?? "#"} target="_blank" rel="noopener noreferrer"
            className="hover:text-foreground transition-colors">
            GitHub ↗
          </a>
        </div>
      </div>

      {/* AI summary */}
      {repo.ai_summary && (
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          {repo.ai_summary}
        </p>
      )}

      {/* Stats row */}
      <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground mb-4">
        {repo.stars_count > 0 && (
          <span className="flex items-center gap-1">★ {repo.stars_count.toLocaleString()} stars</span>
        )}
        {repo.forks_count > 0 && (
          <span>⑂ {repo.forks_count} forks</span>
        )}
        {repo.ast_metadata && (
          <>
            <span>{repo.ast_metadata.function_count} functions</span>
            {repo.ast_metadata.class_count > 0 && <span>{repo.ast_metadata.class_count} classes</span>}
          </>
        )}
        <span>Updated {lastUpdated}</span>
      </div>

      {/* Technologies */}
      {((repo.ast_metadata?.frameworks ?? []).length > 0 || (repo.ast_metadata?.imports ?? []).length > 0) && (
        <div className="flex flex-wrap gap-1.5 mb-4">
          {[...( repo.ast_metadata?.frameworks ?? []), ...(repo.ast_metadata?.imports ?? [])].slice(0, 8).map((tech) => (
            <span key={tech} className="rounded border border-border px-2 py-0.5 text-xs text-muted-foreground font-mono">
              {tech}
            </span>
          ))}
        </div>
      )}

      {/* Topics */}
      {repo.topics.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-4">
          {repo.topics.map((t) => (
            <span key={t} className="rounded-full bg-muted/60 px-2.5 py-0.5 text-xs text-muted-foreground">
              {t}
            </span>
          ))}
        </div>
      )}

      {/* Exports */}
      {(repo.ast_metadata?.exported_symbols ?? []).length > 0 && (
        <div className="border-l-2 border-border pl-4">
          <p className="text-xs text-muted-foreground/60 mb-1.5">Public API</p>
          <div className="flex flex-wrap gap-x-3 gap-y-1">
            {repo.ast_metadata!.exported_symbols.slice(0, 6).map((sym) => (
              <code key={sym} className="text-xs text-muted-foreground font-mono">{sym}</code>
            ))}
            {repo.ast_metadata!.exported_symbols.length > 6 && (
              <span className="text-xs text-muted-foreground/50">+{repo.ast_metadata!.exported_symbols.length - 6} more</span>
            )}
          </div>
        </div>
      )}

      {/* Complexity bar */}
      {complexity > 0 && (
        <div className="mt-4 flex items-center gap-3">
          <span className="text-xs text-muted-foreground/60 shrink-0">Complexity</span>
          <div className="flex-1 h-px bg-border relative">
            <div className="absolute top-1/2 -translate-y-1/2 h-1.5 rounded-full bg-foreground/20 transition-all" style={{ width: `${complexity}%` }} />
          </div>
          <span className="text-xs text-muted-foreground tabular-nums">{complexity}/100</span>
        </div>
      )}
    </article>
  )
}

function extractIntro(mdx: string): string {
  const nextSection = mdx.search(/^## /m)
  return nextSection > -1 ? mdx.slice(0, nextSection) : mdx.slice(0, 600)
}

function extractRest(mdx: string): string {
  const nextSection = mdx.search(/^## /m)
  return nextSection > -1 ? mdx.slice(nextSection) : ""
}
