import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Astra",
  description: "Terms governing your use of Astra.",
};

const sections = [
  {
    id: "the-service",
    title: "The service",
    content: (
      <p>
        Astra (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is an AI-powered developer
        portfolio tool operated by Navin Raj. You connect a GitHub account, select public
        repositories, and Astra performs AST-level analysis, generates technical narratives using
        AI, and publishes a portfolio page at useastra.tech/u/your-github-username. By creating
        an account or using the service, you agree to these terms.
      </p>
    ),
  },
  {
    id: "eligibility",
    title: "Eligibility",
    content: (
      <p>
        You must be at least 13 years old to use Astra, or the minimum age required by the laws
        of your country if higher. By using Astra you represent that you meet this requirement.
        If you are using Astra on behalf of an organisation, you represent that you have authority
        to bind that organisation to these terms.
      </p>
    ),
  },
  {
    id: "early-access",
    title: "Early access",
    content: (
      <>
        <p>
          Astra is currently in early access. The service is functional but evolving. During this
          phase:
        </p>
        <ul>
          <li>Features may be added, changed, or removed without prior notice.</li>
          <li>
            We will make reasonable efforts to preserve generated portfolios and account data,
            but we make no guarantees of uptime or data persistence.
          </li>
          <li>
            Early access is free. Pricing will be introduced before the public launch and
            communicated at least 30 days in advance. Waitlist members retain access at their
            signup terms.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "your-responsibilities",
    title: "Your responsibilities",
    content: (
      <ul>
        <li>
          You must own or have explicit rights to the GitHub repositories you connect to Astra.
          Do not connect repositories you are not authorised to share publicly.
        </li>
        <li>
          You are responsible for reviewing AI-generated portfolio content before publishing and
          for ensuring its accuracy. Astra provides a draft; you are the author of record for
          your published portfolio.
        </li>
        <li>
          You are responsible for the accuracy and legality of any supplementary information you
          provide, including profile details, links, and contact information.
        </li>
        <li>
          You may not use Astra to generate portfolios that misrepresent authorship, impersonate
          other individuals or organisations, contain illegal content, or infringe the intellectual
          property rights of third parties.
        </li>
        <li>
          You may not attempt to reverse-engineer, scrape, or abuse the Astra service in ways
          that damage its performance or security.
        </li>
      </ul>
    ),
  },
  {
    id: "ai-content",
    title: "AI-generated content",
    content: (
      <>
        <p>
          Portfolio narratives are generated by AI models and may contain inaccuracies,
          omissions, or statements that do not fully reflect your work. You are responsible
          for reviewing your portfolio before sharing it. Astra is not liable for errors,
          misrepresentations, or consequences arising from AI-generated content that you
          publish without review.
        </p>
        <p>
          You retain full editorial control. Every sentence can be edited or deleted from
          your dashboard before and after publishing.
        </p>
      </>
    ),
  },
  {
    id: "auto-sync",
    title: "Auto-sync and webhooks",
    content: (
      <p>
        When you enable auto-sync, Astra registers a GitHub webhook on your selected repositories.
        This webhook sends push event metadata to Astra, triggering automatic portfolio updates.
        By enabling auto-sync, you authorise Astra to receive these webhook events from GitHub on
        your behalf. You can disable auto-sync at any time from your dashboard, which will
        de-register the webhook.
      </p>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual property",
    content: (
      <>
        <p>
          You retain full ownership of your source code and any original content you bring to Astra.
          The generated portfolio narratives produced from your repositories are yours to use,
          publish, and share without restriction.
        </p>
        <p>
          Astra retains ownership of its software, design, and infrastructure. You may not
          reproduce or redistribute the Astra platform itself. Astra retains the right to use
          anonymised, aggregated structural patterns (not linked to individual accounts) to improve
          its analysis and AI quality.
        </p>
      </>
    ),
  },
  {
    id: "termination",
    title: "Account termination",
    content: (
      <p>
        You may delete your account at any time from your dashboard settings. Upon deletion,
        your portfolio is unpublished and your data is purged within 14 days. We reserve the
        right to suspend or terminate accounts that violate these terms, with or without notice
        depending on severity.
      </p>
    ),
  },
  {
    id: "disclaimer",
    title: "Disclaimer of warranties",
    content: (
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
        warranty of any kind, express or implied. We do not warrant that the service will be
        uninterrupted, error-free, or that AI-generated content will be accurate, complete, or
        suitable for any particular purpose. We do not warrant that the service will meet your
        specific requirements.
      </p>
    ),
  },
  {
    id: "liability",
    title: "Limitation of liability",
    content: (
      <p>
        To the fullest extent permitted by applicable law, Astra and its operator are not liable
        for any indirect, incidental, special, consequential, or punitive damages arising from
        your use of or inability to use the service — including but not limited to loss of data,
        loss of revenue, or reputational harm — even if advised of the possibility of such damages.
        Our total liability for any claim arising out of or relating to these terms or the service
        will not exceed the amount you paid us in the 12 months prior to the claim.
      </p>
    ),
  },
  {
    id: "governing-law",
    title: "Governing law",
    content: (
      <p>
        These terms are governed by and construed in accordance with the laws of India. Any
        disputes arising under these terms will be subject to the exclusive jurisdiction of the
        courts located in India. If any provision of these terms is found unenforceable, the
        remaining provisions continue in full force.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to these terms",
    content: (
      <p>
        We may update these terms from time to time. We will notify you of material changes
        via the email associated with your account at least 14 days before they take effect.
        Continued use of Astra after that date constitutes acceptance of the revised terms.
        If you do not agree to the revised terms, you may delete your account before they
        take effect.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    content: (
      <p>
        Questions about these terms? Email{" "}
        <a href="mailto:support@useastra.tech" className="text-brand hover:underline font-medium">
          support@useastra.tech
        </a>
        . We aim to respond within 2 business days.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      badge="Terms"
      title="Terms of Service"
      updated="June 19, 2025"
      intro="Clear terms for using Astra. We keep them honest and readable so you know exactly where you stand."
      sections={sections}
      sibling={{ label: "Privacy Policy", href: "/privacy" }}
    />
  );
}

/* ─── Shared Legal Page Shell ────────────────────── */

interface Section {
  id: string;
  title: string;
  content: React.ReactNode;
}

function LegalPage({
  badge,
  title,
  updated,
  intro,
  sections,
  sibling,
}: {
  badge: string;
  title: string;
  updated: string;
  intro: string;
  sections: Section[];
  sibling: { label: string; href: string };
}) {
  return (
    <div>
      {/* Page header */}
      <div className="border-b border-border">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-14 md:py-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand/10 border border-brand/20 text-brand text-[11px] font-semibold uppercase tracking-widest mb-6">
            {badge}
          </div>
          <h1
            className="font-black tracking-tight text-foreground leading-tight mb-5"
            style={{ fontSize: "clamp(2rem, 4.5vw, 3.25rem)", textWrap: "balance" }}
          >
            {title}
          </h1>
          <p className="text-muted-foreground text-base md:text-lg max-w-[52ch] leading-relaxed mb-6">
            {intro}
          </p>
          <div className="flex items-center gap-4 flex-wrap">
            <span className="text-xs text-muted-foreground/60 font-mono">
              Last updated: {updated}
            </span>
            <Link
              href={sibling.href}
              className="text-xs text-brand hover:underline font-medium"
            >
              {sibling.label} &rarr;
            </Link>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-14 md:py-20">
        <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-12 lg:gap-16">

          {/* Sticky TOC */}
          <aside className="hidden lg:block">
            <nav className="sticky top-28 space-y-1">
              <p className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">
                On this page
              </p>
              {sections.map((s) => (
                <a
                  key={s.id}
                  href={`#${s.id}`}
                  className="block text-sm text-muted-foreground hover:text-foreground py-1.5 border-l-2 border-transparent hover:border-brand pl-3 transition-colors duration-150"
                >
                  {s.title}
                </a>
              ))}
              <div className="pt-6 mt-4 border-t border-border">
                <a
                  href="mailto:support@useastra.tech"
                  className="text-xs text-brand hover:underline font-medium"
                >
                  Questions? Email us
                </a>
              </div>
            </nav>
          </aside>

          {/* Content */}
          <div className="space-y-10">
            {sections.map((s, i) => (
              <section
                key={s.id}
                id={s.id}
                className="scroll-mt-28 pb-10 border-b border-border last:border-0 last:pb-0"
              >
                <div className="flex items-baseline gap-4 mb-5">
                  <span className="text-xs font-mono text-muted-foreground/40 tabular-nums w-6 shrink-0">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 className="text-lg md:text-xl font-bold text-foreground">
                    {s.title}
                  </h2>
                </div>
                <div className="pl-10 text-muted-foreground leading-relaxed space-y-4 [&_ul]:space-y-3 [&_ul]:list-none [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:top-[0.6em] [&_li]:before:w-1.5 [&_li]:before:h-1.5 [&_li]:before:rounded-full [&_li]:before:bg-brand/60 [&_strong]:text-foreground [&_strong]:font-semibold [&_a]:text-brand [&_a:hover]:underline">
                  {s.content}
                </div>
              </section>
            ))}
          </div>

        </div>
      </div>
    </div>
  );
}
