import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Astra",
  description: "Terms governing your use of Astra.",
};

const sections = [
  {
    id: "the-service",
    title: "The service",
    content: (
      <p>
        Astra is an AI-powered developer portfolio generator. You connect a GitHub account, select repositories, and Astra analyzes your code, generates technical narratives, and publishes a portfolio page on your behalf.
      </p>
    ),
  },
  {
    id: "early-access",
    title: "Early access",
    content: (
      <p>
        Astra is in early access. The service may change significantly, including features being added, modified, or removed. We will preserve generated portfolios where possible, but we make no guarantees of uptime or data persistence during this phase.
      </p>
    ),
  },
  {
    id: "your-responsibilities",
    title: "Your responsibilities",
    content: (
      <ul>
        <li>
          You must own or have rights to the GitHub repositories you connect. Do not connect repositories you are not authorized to share publicly.
        </li>
        <li>
          You are responsible for the accuracy and legality of supplementary information you provide (bio, links, contact details).
        </li>
        <li>
          You may not use Astra to generate portfolios that misrepresent authorship, contain illegal content, or violate the rights of third parties.
        </li>
      </ul>
    ),
  },
  {
    id: "ai-content",
    title: "AI-generated content",
    content: (
      <p>
        Portfolio content is generated by AI and may contain inaccuracies. You are responsible for reviewing your portfolio before sharing it. Astra is not liable for errors in AI-generated descriptions.
      </p>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual property",
    content: (
      <p>
        You retain ownership of your code and any original content you bring to Astra. The generated portfolio narratives are yours to use. Astra retains the right to use anonymized, aggregated data to improve the service.
      </p>
    ),
  },
  {
    id: "disclaimer",
    title: "Disclaimer of warranties",
    content: (
      <p>
        The service is provided "as is" without warranty of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that AI-generated content will be accurate.
      </p>
    ),
  },
  {
    id: "liability",
    title: "Limitation of liability",
    content: (
      <p>
        To the fullest extent permitted by law, Astra is not liable for indirect, incidental, or consequential damages arising from your use of the service.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to terms",
    content: (
      <p>
        We may update these terms from time to time. Continued use after changes constitutes acceptance of the new terms.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      badge="Terms"
      title="Terms of Service"
      updated="June 2025"
      intro="Clear terms for using Astra. We keep them short so you can actually read them."
      sections={sections}
      sibling={{ label: "Privacy Policy", href: "/privacy" }}
    />
  );
}

/* ─── Shared Legal Page Shell ────────────────────── */

interface Section {
  id: string;
  title: string;
  content: React.ReactNode;
}

function LegalPage({
  badge,
  title,
  updated,
  intro,
  sections,
  sibling,
}: {
  badge: string;
  title: string;
  updated: string;
  intro: string;
  sections: Section[];
  sibling: { label: string; href: string };
}) {
  return (
    <div>
      {/* Page header */}
      <div className="border-b border-border">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-14 md:py-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand/10 border border-brand/20 text-brand text-[11px] font-semibold uppercase tracking-widest mb-6">
            {badge}
          </div>
          <h1
            className="font-black tracking-tight text-foreground leading-tight mb-5"
            style={{ fontSize: "clamp(2rem, 4.5vw, 3.25rem)", textWrap: "balance" }}
          >
            {title}
          </h1>
          <p className="text-muted-foreground text-base md:text-lg max-w-[52ch] leading-relaxed mb-6">
            {intro}
          </p>
          <div className="flex items-center gap-4 flex-wrap">
            <span className="text-xs text-muted-foreground/60 font-mono">
              Last updated: {updated}
            </span>
            <Link
              href={sibling.href}
              className="text-xs text-brand hover:underline font-medium"
            >
              {sibling.label} &rarr;
            </Link>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-14 md:py-20">
        <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-12 lg:gap-16">

          {/* Sticky TOC */}
          <aside className="hidden lg:block">
            <nav className="sticky top-28 space-y-1">
              <p className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">
                On this page
              </p>
              {sections.map((s) => (
                <a
                  key={s.id}
                  href={`#${s.id}`}
                  className="block text-sm text-muted-foreground hover:text-foreground py-1.5 border-l-2 border-transparent hover:border-brand pl-3 transition-colors duration-150"
                >
                  {s.title}
                </a>
              ))}
              <div className="pt-6 mt-4 border-t border-border">
                <a
                  href="mailto:support@useastra.qzz.io"
                  className="text-xs text-brand hover:underline font-medium"
                >
                  Questions? Email us
                </a>
              </div>
            </nav>
          </aside>

          {/* Content */}
          <div className="space-y-10">
            {sections.map((s, i) => (
              <section
                key={s.id}
                id={s.id}
                className="scroll-mt-28 pb-10 border-b border-border last:border-0 last:pb-0"
              >
                <div className="flex items-baseline gap-4 mb-5">
                  <span className="text-xs font-mono text-muted-foreground/40 tabular-nums w-6 shrink-0">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 className="text-lg md:text-xl font-bold text-foreground">
                    {s.title}
                  </h2>
                </div>
                <div className="pl-10 text-muted-foreground leading-relaxed space-y-4 [&_ul]:space-y-3 [&_ul]:list-none [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:top-[0.6em] [&_li]:before:w-1.5 [&_li]:before:h-1.5 [&_li]:before:rounded-full [&_li]:before:bg-brand/60 [&_strong]:text-foreground [&_strong]:font-semibold [&_a]:text-brand [&_a:hover]:underline">
                  {s.content}
                </div>
              </section>
            ))}
          </div>

        </div>
      </div>
    </div>
  );
}
